- name: Ensure IIS is installed and started
  hosts: all
  become: yes
  become_method: runas
  become_user: Administrator
  vars:
    service_name: IIS Admin Service
  tasks:
    - name: Ensure IIS Server is present
      win_feature:
        name: Web-Server
        state: present
